# Analytics Constants
GITHUB_API_BASE_URL = "https://api.github.com"
GITHUB_GRAPHQL_URL = "https://api.github.com/graphql"
DEFAULT_RATE_LIMIT = 5000
RATE_LIMIT_CACHE_TIMEOUT = 300
API_TIMEOUT_SECONDS = 30

CELERY_TASK_RETRY_DELAY = 60
CELERY_MAX_RETRIES = 3

METRICS_REFRESH_THRESHOLD_HOURS = 24
DATA_CLEANUP_DAYS = 90
REFRESH_INTERVAL_MINUTES = 60
